name: mirror

on:
  push:
    branches: ['trying', 'staging', 'master', 'develop']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: mirror
      run: |
          mkdir ~/.ssh
          echo "${GIT_SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          export GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes -o StrictHostKeyChecking=no"
          git remote add mirror "${REMOTE}"
          git push --tags --force --prune mirror 'refs/remotes/origin/*:refs/heads/*'
      env:
        REMOTE: git@gitlab.com:cscs-ci/electronic-structure/SIRIUS.git
        GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_KEY }}
